/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ButtonSize, ButtonVariant } from "./components/ankh-button/ankh-button";
import { IconSize } from "./components/ankh-icon/ankh-icon";
export { ButtonSize, ButtonVariant } from "./components/ankh-button/ankh-button";
export { IconSize } from "./components/ankh-icon/ankh-icon";
export namespace Components {
    interface AnkhButton {
        /**
          * Whether the button is disabled
          * @default false
         */
        "disabled": boolean;
        /**
          * Whether the button should take full width of its container
          * @default false
         */
        "fullWidth": boolean;
        /**
          * The size of the button
          * @default 'medium'
         */
        "size": ButtonSize;
        /**
          * The type attribute for the button
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * The visual style variant of the button
          * @default 'filled'
         */
        "variant": ButtonVariant;
    }
    interface AnkhFocusRing {
        /**
          * Whether to animate inward instead of outward
          * @default false
         */
        "inward": boolean;
        /**
          * Whether the focus ring is visible
          * @default false
         */
        "visible": boolean;
    }
    interface AnkhIcon {
        /**
          * Whether to render the filled variant of the icon. Controls the FILL axis of the Material Symbols variable font.
          * @default false
         */
        "filled": boolean;
        /**
          * Accessible label for meaningful icons. When provided: sets role="img" and aria-label. When omitted: icon is treated as decorative (aria-hidden="true").
         */
        "label"?: string;
        /**
          * Icon name from Material Symbols (e.g. "home", "settings", "favorite"). Uses ligature resolution — the name is rendered as text content and the Material Symbols font converts it to the corresponding glyph.
         */
        "name": string;
        /**
          * The rendered size of the icon. Maps to --icon-size-sm/md/lg/xl tokens with optical size tracking.
          * @default 'md'
         */
        "size": IconSize;
    }
    interface AnkhRipple {
        /**
          * Whether the ripple effect is disabled
          * @default false
         */
        "disabled": boolean;
    }
}
declare global {
    interface HTMLAnkhButtonElement extends Components.AnkhButton, HTMLStencilElement {
    }
    var HTMLAnkhButtonElement: {
        prototype: HTMLAnkhButtonElement;
        new (): HTMLAnkhButtonElement;
    };
    interface HTMLAnkhFocusRingElement extends Components.AnkhFocusRing, HTMLStencilElement {
    }
    var HTMLAnkhFocusRingElement: {
        prototype: HTMLAnkhFocusRingElement;
        new (): HTMLAnkhFocusRingElement;
    };
    interface HTMLAnkhIconElement extends Components.AnkhIcon, HTMLStencilElement {
    }
    var HTMLAnkhIconElement: {
        prototype: HTMLAnkhIconElement;
        new (): HTMLAnkhIconElement;
    };
    interface HTMLAnkhRippleElement extends Components.AnkhRipple, HTMLStencilElement {
    }
    var HTMLAnkhRippleElement: {
        prototype: HTMLAnkhRippleElement;
        new (): HTMLAnkhRippleElement;
    };
    interface HTMLElementTagNameMap {
        "ankh-button": HTMLAnkhButtonElement;
        "ankh-focus-ring": HTMLAnkhFocusRingElement;
        "ankh-icon": HTMLAnkhIconElement;
        "ankh-ripple": HTMLAnkhRippleElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never } | { [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never };

    interface AnkhButton {
        /**
          * Whether the button is disabled
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Whether the button should take full width of its container
          * @default false
         */
        "fullWidth"?: boolean;
        /**
          * The size of the button
          * @default 'medium'
         */
        "size"?: ButtonSize;
        /**
          * The type attribute for the button
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * The visual style variant of the button
          * @default 'filled'
         */
        "variant"?: ButtonVariant;
    }
    interface AnkhFocusRing {
        /**
          * Whether to animate inward instead of outward
          * @default false
         */
        "inward"?: boolean;
        /**
          * Whether the focus ring is visible
          * @default false
         */
        "visible"?: boolean;
    }
    interface AnkhIcon {
        /**
          * Whether to render the filled variant of the icon. Controls the FILL axis of the Material Symbols variable font.
          * @default false
         */
        "filled"?: boolean;
        /**
          * Accessible label for meaningful icons. When provided: sets role="img" and aria-label. When omitted: icon is treated as decorative (aria-hidden="true").
         */
        "label"?: string;
        /**
          * Icon name from Material Symbols (e.g. "home", "settings", "favorite"). Uses ligature resolution — the name is rendered as text content and the Material Symbols font converts it to the corresponding glyph.
         */
        "name": string;
        /**
          * The rendered size of the icon. Maps to --icon-size-sm/md/lg/xl tokens with optical size tracking.
          * @default 'md'
         */
        "size"?: IconSize;
    }
    interface AnkhRipple {
        /**
          * Whether the ripple effect is disabled
          * @default false
         */
        "disabled"?: boolean;
    }

    interface AnkhButtonAttributes {
        "variant": ButtonVariant;
        "size": ButtonSize;
        "fullWidth": boolean;
        "disabled": boolean;
        "type": 'button' | 'submit' | 'reset';
    }
    interface AnkhFocusRingAttributes {
        "visible": boolean;
        "inward": boolean;
    }
    interface AnkhIconAttributes {
        "name": string;
        "size": IconSize;
        "filled": boolean;
        "label": string;
    }
    interface AnkhRippleAttributes {
        "disabled": boolean;
    }

    interface IntrinsicElements {
        "ankh-button": Omit<AnkhButton, keyof AnkhButtonAttributes> & { [K in keyof AnkhButton & keyof AnkhButtonAttributes]?: AnkhButton[K] } & { [K in keyof AnkhButton & keyof AnkhButtonAttributes as `attr:${K}`]?: AnkhButtonAttributes[K] } & { [K in keyof AnkhButton & keyof AnkhButtonAttributes as `prop:${K}`]?: AnkhButton[K] };
        "ankh-focus-ring": Omit<AnkhFocusRing, keyof AnkhFocusRingAttributes> & { [K in keyof AnkhFocusRing & keyof AnkhFocusRingAttributes]?: AnkhFocusRing[K] } & { [K in keyof AnkhFocusRing & keyof AnkhFocusRingAttributes as `attr:${K}`]?: AnkhFocusRingAttributes[K] } & { [K in keyof AnkhFocusRing & keyof AnkhFocusRingAttributes as `prop:${K}`]?: AnkhFocusRing[K] };
        "ankh-icon": Omit<AnkhIcon, keyof AnkhIconAttributes> & { [K in keyof AnkhIcon & keyof AnkhIconAttributes]?: AnkhIcon[K] } & { [K in keyof AnkhIcon & keyof AnkhIconAttributes as `attr:${K}`]?: AnkhIconAttributes[K] } & { [K in keyof AnkhIcon & keyof AnkhIconAttributes as `prop:${K}`]?: AnkhIcon[K] } & OneOf<"name", AnkhIcon["name"], AnkhIconAttributes["name"]>;
        "ankh-ripple": Omit<AnkhRipple, keyof AnkhRippleAttributes> & { [K in keyof AnkhRipple & keyof AnkhRippleAttributes]?: AnkhRipple[K] } & { [K in keyof AnkhRipple & keyof AnkhRippleAttributes as `attr:${K}`]?: AnkhRippleAttributes[K] } & { [K in keyof AnkhRipple & keyof AnkhRippleAttributes as `prop:${K}`]?: AnkhRipple[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ankh-button": LocalJSX.IntrinsicElements["ankh-button"] & JSXBase.HTMLAttributes<HTMLAnkhButtonElement>;
            "ankh-focus-ring": LocalJSX.IntrinsicElements["ankh-focus-ring"] & JSXBase.HTMLAttributes<HTMLAnkhFocusRingElement>;
            "ankh-icon": LocalJSX.IntrinsicElements["ankh-icon"] & JSXBase.HTMLAttributes<HTMLAnkhIconElement>;
            "ankh-ripple": LocalJSX.IntrinsicElements["ankh-ripple"] & JSXBase.HTMLAttributes<HTMLAnkhRippleElement>;
        }
    }
}
