/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ButtonSize, ButtonVariant } from "./components/ankh-button/ankh-button";
export { ButtonSize, ButtonVariant } from "./components/ankh-button/ankh-button";
export namespace Components {
    interface AnkhButton {
        /**
          * Whether the button is disabled
          * @default false
         */
        "disabled": boolean;
        /**
          * Whether the button should take full width of its container
          * @default false
         */
        "fullWidth": boolean;
        /**
          * The size of the button
          * @default 'medium'
         */
        "size": ButtonSize;
        /**
          * The type attribute for the button
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * The visual style variant of the button
          * @default 'filled'
         */
        "variant": ButtonVariant;
    }
    interface AnkhFocusRing {
        /**
          * Whether to animate inward instead of outward
          * @default false
         */
        "inward": boolean;
        /**
          * Whether the focus ring is visible
          * @default false
         */
        "visible": boolean;
    }
    interface AnkhRipple {
        /**
          * Whether the ripple effect is disabled
          * @default false
         */
        "disabled": boolean;
    }
}
declare global {
    interface HTMLAnkhButtonElement extends Components.AnkhButton, HTMLStencilElement {
    }
    var HTMLAnkhButtonElement: {
        prototype: HTMLAnkhButtonElement;
        new (): HTMLAnkhButtonElement;
    };
    interface HTMLAnkhFocusRingElement extends Components.AnkhFocusRing, HTMLStencilElement {
    }
    var HTMLAnkhFocusRingElement: {
        prototype: HTMLAnkhFocusRingElement;
        new (): HTMLAnkhFocusRingElement;
    };
    interface HTMLAnkhRippleElement extends Components.AnkhRipple, HTMLStencilElement {
    }
    var HTMLAnkhRippleElement: {
        prototype: HTMLAnkhRippleElement;
        new (): HTMLAnkhRippleElement;
    };
    interface HTMLElementTagNameMap {
        "ankh-button": HTMLAnkhButtonElement;
        "ankh-focus-ring": HTMLAnkhFocusRingElement;
        "ankh-ripple": HTMLAnkhRippleElement;
    }
}
declare namespace LocalJSX {
    interface AnkhButton {
        /**
          * Whether the button is disabled
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Whether the button should take full width of its container
          * @default false
         */
        "fullWidth"?: boolean;
        /**
          * The size of the button
          * @default 'medium'
         */
        "size"?: ButtonSize;
        /**
          * The type attribute for the button
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * The visual style variant of the button
          * @default 'filled'
         */
        "variant"?: ButtonVariant;
    }
    interface AnkhFocusRing {
        /**
          * Whether to animate inward instead of outward
          * @default false
         */
        "inward"?: boolean;
        /**
          * Whether the focus ring is visible
          * @default false
         */
        "visible"?: boolean;
    }
    interface AnkhRipple {
        /**
          * Whether the ripple effect is disabled
          * @default false
         */
        "disabled"?: boolean;
    }

    interface AnkhButtonAttributes {
        "variant": ButtonVariant;
        "size": ButtonSize;
        "fullWidth": boolean;
        "disabled": boolean;
        "type": 'button' | 'submit' | 'reset';
    }
    interface AnkhFocusRingAttributes {
        "visible": boolean;
        "inward": boolean;
    }
    interface AnkhRippleAttributes {
        "disabled": boolean;
    }

    interface IntrinsicElements {
        "ankh-button": Omit<AnkhButton, keyof AnkhButtonAttributes> & { [K in keyof AnkhButton & keyof AnkhButtonAttributes]?: AnkhButton[K] } & { [K in keyof AnkhButton & keyof AnkhButtonAttributes as `attr:${K}`]?: AnkhButtonAttributes[K] } & { [K in keyof AnkhButton & keyof AnkhButtonAttributes as `prop:${K}`]?: AnkhButton[K] };
        "ankh-focus-ring": Omit<AnkhFocusRing, keyof AnkhFocusRingAttributes> & { [K in keyof AnkhFocusRing & keyof AnkhFocusRingAttributes]?: AnkhFocusRing[K] } & { [K in keyof AnkhFocusRing & keyof AnkhFocusRingAttributes as `attr:${K}`]?: AnkhFocusRingAttributes[K] } & { [K in keyof AnkhFocusRing & keyof AnkhFocusRingAttributes as `prop:${K}`]?: AnkhFocusRing[K] };
        "ankh-ripple": Omit<AnkhRipple, keyof AnkhRippleAttributes> & { [K in keyof AnkhRipple & keyof AnkhRippleAttributes]?: AnkhRipple[K] } & { [K in keyof AnkhRipple & keyof AnkhRippleAttributes as `attr:${K}`]?: AnkhRippleAttributes[K] } & { [K in keyof AnkhRipple & keyof AnkhRippleAttributes as `prop:${K}`]?: AnkhRipple[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ankh-button": LocalJSX.IntrinsicElements["ankh-button"] & JSXBase.HTMLAttributes<HTMLAnkhButtonElement>;
            "ankh-focus-ring": LocalJSX.IntrinsicElements["ankh-focus-ring"] & JSXBase.HTMLAttributes<HTMLAnkhFocusRingElement>;
            "ankh-ripple": LocalJSX.IntrinsicElements["ankh-ripple"] & JSXBase.HTMLAttributes<HTMLAnkhRippleElement>;
        }
    }
}
